### ISSUE TITLE
amber.siz not found

### ISSUE THREAD

**Issue by Samuel-gwb** [regeneron-mpds/propermab#1]
Hi, I cannot find amber.siz in the nanoshaper (https://gitlab.iit.it/SDecherchi/nanoshaper). 
Could you give a detailed address? thanks!

**Comment by yx0516** [comment]
Hi, I also have the same question.

**Comment by bianli-regn** [comment]
@yx0516 @Samuel-gwb Thanks for your interest in this work. The link to the amber.siz file has now been updated in the README.
