### ISSUE TITLE
how to use the results

### ISSUE THREAD

**Issue by kehan777** [regeneron-mpds/propermab#3]
{
'hyd_asa': 5792.08784994631,
'hph_asa': 4324.256925727055,
'net_charge': 2.0000000000000115,
'exposed_net_charge': -54.84999999999924,
'net_charge_cdr': 2.000000000000003,
'exposed_net_charge_cdr': -25.63,
'dipole_moment': 312.18610463483503,
'Fv_chml': 2.0,
'exposed_Fv_chml': -0.8500000000000014,
'hyd_moment': 466.79625177367046,
'cdr_h3_length': 13,
'aromatic_asa': 1063.019991846332,
'aromatic_cdr': 20,
'exposed_aromatic': 17,
'scm': 759.7550000000001,
'pos_ann_index': 1.0665034712376378,
'neg_ann_index': 1.219596326092563,
'aromatic_ann_index': 1.0360600326380085,
'pos_ripley_k': 1.0109179134654267,
'neg_ripley_k': 0.2827254735651682,
'aromatic_ripley_k': 1.4289797084881397,
'hyd_patch_area': 784.9276860382015,
'pos_patch_area': 74.91919133774987,
'neg_patch_area': 250.58775706865893,
'hyd_patch_area_cdr': 282.20901227528475,
'pos_patch_area_cdr': 74.91919133774987,
'neg_patch_area_cdr': 83.7257676014706,
'heiden_score': 137.98536008011325
}

Can you please  share the average, max, min values of those features for therapy mabs

**Comment by yx0516** [comment]
@kehan777  Hi,  did you successfully run this repo?  The file 'amber.siz' where did you get it ? Could you share with us?

**Comment by bianli-regn** [comment]
@kehan777 Thanks for your interest in the work. Details regarding the features are described in this preprint: https://www.biorxiv.org/content/10.1101/2024.10.10.616558v2.
