### ISSUE TITLE
should i prepare pdb by pdbfixer or other script?

### ISSUE THREAD

**Issue by kehan777** [regeneron-mpds/propermab#4]
file contents of test.py
from propermab import defaults
from propermab.features import feature_utils
defaults.system_config.update_from_json('./default_config.json')
mol_feature = feature_utils.calculate_features_from_pdb('./tests/1a14_k.pdb')

and run it $ python test.py

Traceback (most recent call last):
  File "test.py", line 6, in <module>
    mol_feature = feature_utils.calculate_features_from_pdb('/mnt/d/propermab/tests/1a14_k.pdb')
  File "/mnt/d/propermab/propermab/features/feature_utils.py", line 315, in calculate_features_from_pdb
    net_charge = featurizer.net_charge()
  File "/mnt/d/propermab/propermab/features/struct_featurizer.py", line 169, in net_charge
    for _, chain_atom_charges in self.atom_charges.items():
  File "/mnt/d/propermab/propermab/features/struct_featurizer.py", line 151, in atom_charges
    system, topology = self.system_and_topology
  File "/mnt/d/propermab/propermab/features/struct_featurizer.py", line 164, in system_and_topology
    self._system_and_topology = md.simple_system(self.pdb_file)
  File "/mnt/d/propermab/propermab/structure/md.py", line 77, in simple_system
    system = forcefield.createSystem(
  File "/home/miniconda/install/envs/propermab/lib/python3.8/site-packages/openmm/app/forcefield.py", line 1251, in createSystem
    templateForResidue = self._matchAllResiduesToTemplates(data, topology, residueTemplates, ignoreExternalBonds)
  File "/home/miniconda/install/envs/propermab/lib/python3.8/site-packages/openmm/app/forcefield.py", line 1466, in _matchAllResiduesToTemplates
    raise ValueError('No template found for residue %d (%s).  %s  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template' % (res.index+1, res.name, _findMatchErrors(self, res)))
ValueError: No template found for residue 1 (GLN).  The set of atoms is similar to GLN, but it is missing 3 hydrogen atoms.  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template

**Comment by kehan777** [comment]
1

**Comment by aaaaaaaaa21-code** [comment]
> file contents of test.py from propermab import defaults from propermab.features import feature_utils defaults.system_config.update_from_json('./default_config.json') mol_feature = feature_utils.calculate_features_from_pdb('./tests/1a14_k.pdb')
> 
> and run it $ python test.py
> 
> Traceback (most recent call last): File "test.py", line 6, in mol_feature = feature_utils.calculate_features_from_pdb('/mnt/d/propermab/tests/1a14_k.pdb') File "/mnt/d/propermab/propermab/features/feature_utils.py", line 315, in calculate_features_from_pdb net_charge = featurizer.net_charge() File "/mnt/d/propermab/propermab/features/struct_featurizer.py", line 169, in net_charge for _, chain_atom_charges in self.atom_charges.items(): File "/mnt/d/propermab/propermab/features/struct_featurizer.py", line 151, in atom_charges system, topology = self.system_and_topology File "/mnt/d/propermab/propermab/features/struct_featurizer.py", line 164, in system_and_topology self._system_and_topology = md.simple_system(self.pdb_file) File "/mnt/d/propermab/propermab/structure/md.py", line 77, in simple_system system = forcefield.createSystem( File "/home/miniconda/install/envs/propermab/lib/python3.8/site-packages/openmm/app/forcefield.py", line 1251, in createSystem templateForResidue = self._matchAllResiduesToTemplates(data, topology, residueTemplates, ignoreExternalBonds) File "/home/miniconda/install/envs/propermab/lib/python3.8/site-packages/openmm/app/forcefield.py", line 1466, in _matchAllResiduesToTemplates raise ValueError('No template found for residue %d (%s). %s For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template' % (res.index+1, res.name, _findMatchErrors(self, res))) ValueError: No template found for residue 1 (GLN). The set of atoms is similar to GLN, but it is missing 3 hydrogen atoms. For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template

Hello, I encountered the same issue and was wondering if you could share how to resolve it?
